export const USER_REPO = "USER_REPO"
export const SHOW_BOX = "SHOW_BOX"
export const HIDE_BOX = "HIDE_BOX"
export const REPO_DETAILS = "REPO_DETAILS"
export const REPO_ISSUES_DETAILS = "REPO_ISSUES_DETAILS"
export const COMMITS_DETAILS = "COMMITS_DETAILS"
export const DELETE_REPO = "DELETE_REPO"